# Generated by Django 3.0.13 on 2021-09-10 12:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('log_def', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dictdefine',
            name='create_datetime',
            field=models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='创建时间'),
        ),
        migrations.AlterField(
            model_name='logdefine',
            name='create_datetime',
            field=models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='创建时间'),
        ),
    ]
