# Generated by Django 3.1.10 on 2023-03-07 17:55

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('log_def', '0002_auto_20210910_1211'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dictdefine',
            name='key',
            field=models.CharField(db_index=True, max_length=50, unique=True, validators=[django.core.validators.RegexValidator('[\\d\\w_]+$', '字母组合,符合^[a-z][\\d\\w_]+$')], verbose_name='标识名'),
        ),
        migrations.AlterField(
            model_name='logdefine',
            name='key',
            field=models.CharField(db_index=True, max_length=100, validators=[django.core.validators.RegexValidator('[\\d\\w_]+$', '字母组合,符合^[a-z][\\d\\w_]+$')], verbose_name='日志表标识'),
        ),
    ]
