# Generated by Django 2.0.13 on 2021-02-25 13:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myadmin', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='status',
            field=models.IntegerField(choices=[(0, '正常'), (1, '锁定'), (2, '删除'), (3, '未激活'), (4, '错误'), (5, '离职')], default=3, help_text='登录状态', verbose_name='状态'),
        ),
    ]
