# Generated by Django 3.1.7 on 2021-03-26 11:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myadmin', '0003_auto_20210325_1530'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='password',
            field=models.CharField(blank=True, db_index=True, max_length=64, verbose_name='密码'),
        ),
    ]
