# Generated by Django 3.0.13 on 2021-03-31 09:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myadmin', '0004_auto_20210326_1130'),
    ]

    operations = [
        migrations.AlterField(
            model_name='role',
            name='type',
            field=models.IntegerField(choices=[(1, '角色'), (2, '组织'), (3, '权限集合')], default=1, verbose_name='类型'),
        ),
    ]
