# Generated by Django 3.0.13 on 2021-04-01 14:52

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import framework.models


class Migration(migrations.Migration):

    dependencies = [
        ('myadmin', '0005_auto_20210331_0933'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='useroauth',
            name='user_id',
        ),
        migrations.AddField(
            model_name='useroauth',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='所属管理员'),
        ),
        migrations.AlterField(
            model_name='useroauth',
            name='other_info',
            field=framework.models.JSONField(default='{}', verbose_name='其他信息'),
        ),
    ]
