# Generated by Django 3.0.13 on 2021-09-14 13:02

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myadmin', '0007_auto_20210910_1211'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='operatelog',
            name='user_id',
        ),
        migrations.AddField(
            model_name='operatelog',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL, verbose_name='管理员ID'),
        ),
    ]
