# Generated by Django 2.0.13 on 2021-02-21 17:39

from django.db import migrations, models
import framework.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SyncModel',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('_version', models.IntegerField(default=0, verbose_name='版本')),
                ('create_datetime', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('update_datetime', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('name', models.CharField(default='', max_length=100, verbose_name='名称')),
                ('url', models.CharField(default='', max_length=200, verbose_name='同步后台的地址')),
                ('key', models.CharField(blank=True, default='', max_length=20)),
            ],
            options={
                'ordering': ('id',),
            },
            bases=(models.Model, framework.models.SqlModelMixin),
        ),
    ]
