# Generated by Django 3.0.13 on 2021-04-01 00:33

import django.core.validators
from django.db import migrations, models
import framework.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AccessDomain',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('_version', models.IntegerField(default=0, verbose_name='版本')),
                ('create_datetime', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('update_datetime', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('name', models.CharField(max_length=100, unique=True, validators=[django.core.validators.RegexValidator('^[a-z][\\d\\w_]+$', '字母组合,符合^[a-z][\\d\\w_]+$')], verbose_name='名称')),
                ('alias', models.CharField(blank=True, default='', max_length=100, verbose_name='别名')),
                ('bindpw', models.CharField(default='', max_length=30, verbose_name='访问密钥')),
                ('access_address', models.CharField(default='', max_length=256, verbose_name='访问地址')),
            ],
            bases=(models.Model, framework.models.SqlModelMixin),
        ),
    ]
