# Generated by Django 3.0.13 on 2021-04-01 14:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myadmin', '0006_auto_20210401_1452'),
        ('ldap_account', '0002_accessdomain_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='accessdomain',
            name='role',
            field=models.ManyToManyField(to='myadmin.Role', verbose_name='允许访问的角色'),
        ),
    ]
