# Generated by Django 3.0.13 on 2021-09-10 12:11

from django.db import migrations, models
import framework.models


class Migration(migrations.Migration):

    dependencies = [
        ('analysis', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='QueryServer',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('_version', models.IntegerField(default=0, verbose_name='版本')),
                ('create_datetime', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='创建时间')),
                ('update_datetime', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('name', models.CharField(max_length=20, verbose_name='服务器名称')),
                ('alias', models.CharField(db_index=True, default='', max_length=20, verbose_name='服务器别名')),
                ('log_db_config', models.CharField(max_length=500, verbose_name='日志数据库')),
                ('host', models.CharField(max_length=200, verbose_name='地址')),
                ('user', models.CharField(max_length=100, verbose_name='用户')),
                ('password', models.CharField(max_length=100, verbose_name='密码')),
                ('port', models.IntegerField(default=3306, verbose_name='端口')),
                ('db_name', models.CharField(max_length=100, verbose_name='数据库名')),
                ('charset', models.CharField(default='utf8', max_length=100, verbose_name='数据库名')),
                ('status', models.IntegerField(choices=[(-1, '已删除'), (0, '正常')], default=0, verbose_name='服务器状态')),
                ('remark', models.CharField(max_length=200, verbose_name='备注')),
                ('order', models.IntegerField(default=0, verbose_name='排序')),
            ],
            options={
                'ordering': ('order',),
            },
            bases=(models.Model, framework.models.BaseModelMixin),
        ),
        migrations.AlterField(
            model_name='query',
            name='create_datetime',
            field=models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='创建时间'),
        ),
        migrations.AlterField(
            model_name='statistic',
            name='create_datetime',
            field=models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='创建时间'),
        ),
    ]
